# For more info on HTTP files go to https://aka.ms/vs/httpfile
@base_url=http://localhost:8083

GET {{base_url}}/connectors/

###

POST {{base_url}}/connectors/
Content-Type: application/json

{
  "name": "opensearch-students-sink",
  "config": {
    "connector.class": "io.aiven.kafka.connect.opensearch.OpensearchSinkConnector",
    "connection.url": "http://opensearch:9200",
    "topics": "students1",
    "tasks.max":"1",
    "key.ignore": "true",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "schema.ignore": "true",
    "transforms": "TimestampRouter",
    "transforms.TimestampRouter.topic.format": "${topic}-${timestamp}",
    "transforms.TimestampRouter.timestamp.format": "yyyy-MM-dd",
    "transforms.TimestampRouter.type": "org.apache.kafka.connect.transforms.TimestampRouter"
  }
}

###
